backend:
  name: git-gateway
  branch: main

media_folder: "static/img"
public_folder: "/img"

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Extended Description", name: "description", widget: "markdown", required: false }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - { label: "Feature Image", name: "thumbnail", widget: "image", required: false }
      - { label: "YouTube Video URL", name: "video", widget: "string", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
